# Generated by Django 4.1.5 on 2023-03-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionandAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=500)),
                ('question2', models.CharField(max_length=500)),
                ('question3', models.CharField(max_length=500)),
                ('question4', models.CharField(max_length=500)),
                ('question5', models.CharField(max_length=500)),
                ('answer1', models.CharField(max_length=500)),
                ('answer2', models.CharField(max_length=500)),
                ('answer3', models.CharField(max_length=500)),
                ('answer4', models.CharField(max_length=500)),
                ('answer5', models.CharField(max_length=500)),
            ],
        ),
    ]
