# Generated by Django 4.2 on 2023-04-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0004_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='user',
            new_name='username',
        ),
    ]
