# Generated by Django 4.2 on 2023-04-15 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answerapp', '0007_studentrollno_delete_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRollNo',
            new_name='UserProfile',
        ),
    ]
