# Generated by Django 4.2 on 2023-04-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0008_rename_studentrollno_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='rollno',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='answerapp.userprofile'),
            preserve_default=False,
        ),
    ]
