# Generated by Django 4.2 on 2023-04-17 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0010_alter_studentresult_rollno_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
