# Generated by Django 4.2 on 2023-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0013_studentresult_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='question1',
            field=models.TextField(),
        ),
    ]
