# Generated by Django 4.2 on 2023-04-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerapp', '0014_alter_questionandanswer_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='answer9',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question10',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question4',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question5',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question6',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question7',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question8',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionandanswer',
            name='question9',
            field=models.TextField(),
        ),
    ]
